name: Notify Feature A

on:
  push:
    branches:
      - feature_a

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Cambios subidos a rama feature_a
          to: correo-destino@gmail.com
          from: ${{ secrets.MAIL_USERNAME }}
          body: Se han subido cambios a la rama feature_a del repositorio.